import { UserRole } from '../models/User';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  ADMIN: [
    'dashboard.read',
    'stations.read',
    'stations.manage',
    'pumps.read',
    'pumps.manage',
    'tanks.read',
    'tanks.manage',
    'products.read',
    'products.manage',
    'purchases.read',
    'purchases.manage',
    'sales.read',
    'sales.manage',
    'expenses.read',
    'expenses.manage',
    'shifts.read',
    'shifts.manage',
    'services.manage',
    'reports.read',
    'daily-closure.manage',
    'kif-returns.manage',
    'suppliers.read',
    'suppliers.manage',
    'customers.read',
    'customers.manage',
    'users.read',
    'users.manage',
  ],
  MANAGER: [
    'dashboard.read',
    'stations.read',
    'stations.manage',
    'pumps.read',
    'pumps.manage',
    'tanks.read',
    'tanks.manage',
    'products.read',
    'products.manage',
    'purchases.read',
    'purchases.manage',
    'sales.read',
    'sales.manage',
    'expenses.read',
    'expenses.manage',
    'shifts.read',
    'shifts.manage',
    'services.manage',
    'reports.read',
    'daily-closure.manage',
    'kif-returns.manage',
    'suppliers.read',
    'suppliers.manage',
    'customers.read',
    'customers.manage',
    'users.read',
  ],
  SUPERVISOR: [
    'dashboard.read',
    'stations.read',
    'pumps.read',
    'tanks.read',
    'products.read',
    'purchases.read',
    'sales.read',
    'sales.manage',
    'expenses.read',
    'shifts.read',
    'shifts.manage',
    'services.manage',
    'reports.read',
    'daily-closure.manage',
    'kif-returns.manage',
    'suppliers.read',
    'customers.read',
    'users.read',
  ],
  OPERATOR: [
    'dashboard.read',
    'stations.read',
    'pumps.read',
    'tanks.read',
    'products.read',
    'purchases.read',
    'sales.read',
    'sales.manage',
    'expenses.read',
    'shifts.read',
    'shifts.manage',
    'services.manage',
    'reports.read',
  ],
};

export const getRolePermissions = (role: UserRole): string[] => ROLE_PERMISSIONS[role] || [];
